<?php include _VIEW_PATH . "/components/header.phtml";?> 
<main class="col">
        <div class="container mt-3 diag">
          <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-md-8 col-lg-6">
              <!-- Carte Bootstrap pour styliser le graphique -->
              <div class="card diag-param">
                <div class="card-body projet-diagramme">
                  <canvas id="projectsChart"></canvas>
                </div>
              </div>
            </div>
          </div>
        </div>
</main>
<?php include _VIEW_PATH . "/components/footer-collabs-stats.phtml";?> 