<?php include _VIEW_PATH . "/components/header.phtml";?> 
<main class="col">
                    <div class="params row mt-5">
                        <div class="col col-xl-4 mb-2">
                            <div class="card card-param">
                                <div class="card-head">
                                    <h5 class="card-title text-center title-card">Liste des postes</h5>
                                </div>
                                <div class="card-body projectBackground">
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light">
                                        <span>Chef de projet</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Système admin</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Développeur</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Testeur</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Stager</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Project management</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-2">
                                        <button type="button" data-bs-toggle="modal" data-bs-target="#modal_post" class="btn btn-sm projectButton border border-light button-text ">
                                            <i class="bi bi-plus button-icon"></i> 
                                            Ajouter un poste
                                        </button>
                                        <div class="modal fade" id="modal_post" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered">
                                              <div class="modal-content modalContent">
                                                <div class="modal-header">
                                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <label class="fs-5 mb-2">Ajouter un poste :</label> 
                                                    <input type="text" class="w-100 form-control rounded" id="floatingInput" placeholder="Intitulé du poste">
                                                    <label class="fs-5 mb-2">Technologies utilisées :</label>
                                                    <select class="form-select rounded" id="floatingSelect">
                                                        <option value="0" selected>Web</option>
                                                        <option value="1">Mobile</option>
                                                        <option value="2">Java</option>
                                                        <option value="3">Autre</option>
                                                    </select>
                                                </div>
                                                <div class="modal-footer">
                                                  <button type="button" class="btn modal_exit" data-bs-dismiss="modal">Fermer</button>
                                                  <button type="button" class="btn modal_confirm">Confirmer</button>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                    </div>
                                </div>
                            </div>
                        </div>
    
                        <div class="col col-xl-4 mb-2">
                            <div class="card card-param">
                                <div class="card-head">
                                    <h5 class="card-title text-center title-card">Liste des technologies</h5>
                                </div>
                                <div class="card-body projectBackground">
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light">
                                        <span>Web</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Mobile</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Java</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>React</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>PHP</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Jquery</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-2">
                                        <button type="button" data-bs-toggle="modal" data-bs-target="#modal_techno" class="btn btn-sm projectButton border border-light button-text ">
                                            <i class="bi bi-plus button-icon"></i> 
                                            Ajouter une technologie
                                        </button>
                                        <div class="modal fade" id="modal_techno" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered">
                                              <div class="modal-content modalContent">
                                                <div class="modal-header">
                                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <label class="fs-5 mb-2">Ajouter une technologie :</label> 
                                                    <input type="text" class="w-100 form-control rounded" id="floatingInput" placeholder="Technologie voulu ...">
                                                </div>
                                                <div class="modal-footer">
                                                  <button type="button" class="btn modal_exit" data-bs-dismiss="modal">Fermer</button>
                                                  <button type="button" class="btn modal_confirm">Confirmer</button>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                    </div>
                                </div>
                            </div>
                        </div>
    
                        <div class="col col-xl-4 mb-2">
                            <div class="card card-param">
                                <div class="card-head">
                                    <h5 class="card-title text-center title-card">Liste des rôles</h5>
                                </div>
                                <div class="card-body projectBackground">
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light">
                                        <span>Gestionnaire de projet</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Lead développeur</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Analyste</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Designer</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Dev ops</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-between align-items-center card-text border border-light mt-3">
                                        <span>Scrum Master</span>
                                            <div>
                                                <i class="bi bi-pen-fill"></i>
                                                <i class="bi bi-trash-fill"></i>
                                            </div>
                                          </div>
                                    <div class="d-flex justify-content-end position-absolute bottom-0 end-0 p-2">
                                        <button type="button" data-bs-toggle="modal" data-bs-target="#modal_role" class="btn btn-sm projectButton border border-light button-text ">
                                            <i class="bi bi-plus button-icon"></i> 
                                            Ajouter un rôle
                                        </button>
                                        <div class="modal fade" id="modal_role" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered">
                                              <div class="modal-content modalContent">
                                                <div class="modal-header">
                                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <label class="fs-5 mb-2">Ajouter un rôle :</label> 
                                                        <select class="form-select rounded" id="floatingSelect">
                                                            <option value="1">Gestionnaire de projet</option>
                                                            <option value="2">Lead développeur</option>
                                                            <option value="3">Analyste</option>
                                                            <option value="4">Designer</option>
                                                            <option value="5">Dev ops</option>
                                                            <option value="6">Scrum Master</option>
                                                        </select>
                                                        <label class="fs-5 mb-2">Modules affectés :</label> 
                                                            <select class="form-select rounded" id="floatingSelect">
                                                                <option value="0" selected>Projet</option>
                                                                <option value="1">Mes tâches</option>
                                                                <option value="2">Statistiques collaborateurs</option>
                                                                <option value="3">Statistiques projets</option>
                                                                <option value="4">Collaborateurs</option>
                                                                <option value="5">Traçabilité</option>
                                                                <option value="6">Paramètres</option>
                                                            </select>
                                                </div>
                                                <div class="modal-footer">
                                                  <button type="button" class="btn modal_exit" data-bs-dismiss="modal">Fermer</button>
                                                  <button type="button" class="btn modal_confirm">Confirmer</button>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
<?php include _VIEW_PATH . "/components/footer.phtml";?> 