<?php include _VIEW_PATH . "/components/header.phtml";?>
<main class="col">
                <div class="table-responsive table_resp_pos ms-4">
                    <table class="table proj-table mt-5 text-center"> 
                            <thead>
                                <tr class="">
                                    <th scope="col">N°</th>
                                    <th scope="col">Référence</th>
                                    <th scope="col">Action</th>
                                    <th scope="col">Auteur</th>
                                    <th scope="col">Date</th>
                                    
                                    
                                   
                                </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="col">Projet 1</td>
                                
                                <td class="col">x</td>
                                <td class="col">Création Projet</td>
                                <td class="col">John D</td>
                                <td class="col">jj/mm/aaaa</td>
                                
                                
                                
                                
                            </tr>
                            <tr>
                                <td>Projet 2</td>
                                
                                <td>x</td>
                                <td>Archivage projet</td>
                                <td>Paul B</td>
                                <td>jj/mm/YYYY</td>
                               
                                
                                
                            </tr>
                            <tr>
                                <td>Projet 3</td>
                                
                                <td>x</td>
                                <td>Archivage projet</td>
                                <td>Paul B</td>
                                <td>jj/mm/YYYY</td>
                               
                                
                                
                            </tr>
                            <tr>
                                <td>Projet 4</td>
                                
                                <td>x</td>
                                <td>Archivage projet</td>
                                <td>Paul B</td>
                                <td>jj/mm/YYYY</td>
                                
                                
                                
                            </tr>
                            <tr>
                                <td>Projet 5</td>
                                
                                <td>x</td>
                                <td>Archivage projet</td>
                                <td>Paul B</td>
                                <td>jj/mm/YYYY</td>
                               
                                
                                
                            </tr>
                            <tr>
                                <td>Projet 6</td>
                                
                                <td>x</td>
                                <td>Archivage projet</td>
                                <td>Paul B</td>
                                <td>jj/mm/YYYY</td>
                                
                                
                            </tr>
                        </tbody>
                    </table>
                </div>
            </main> 
<?php include _VIEW_PATH . "/components/footer.phtml";?> 