<?php include _VIEW_PATH . "/components/headerManager.phtml";?>
          
<main class="col">
                <div class="row filter__section mt-4">
                    <div class="col-0 col-lg-5 col-md-4 col-1"></div>
                    <div class="col-1 col-lg-1 col-md-2 col">
                        <button id="filterBtn" class="btn filterButton fontWhite">Filtrer</button>
                    </div>
                  <div class="col-2 col-lg-3 col-md-3 col">
                    <input type="text" class="form-control dateControl" id="startDate" placeholder="Date">
                  </div>
                  <div class="col-1 col-lg-3 col-md-3 col">
                    <input type="text" class="form-control dateControl" id="endDate" placeholder="Date">
                  </div>
                </div>
                <div id="dataDisplay" class="">
                  <!-- Ici on montre les données, le target du script étant l'id datadisplay.
                   Voir dans le script :
                   data.forEach(item => {
                  dataDisplay.append(`<p>${item.name} - ${item.date}</p>`);-->
                </div>
                <div class="upper_table ms-4">
                    <i class="bi bi-pencil-square fs-4"></i>
                    <span class="edit_table">Modifier le tableau</span>
                </div>
                <div class="table-responsive table_resp_pos ms-4">
                    <table class="table proj-table mt-2 text-center">
                        <thead>
                            <tr class="">
                                <th scope="col">Nom</th>
                                <th scope="col">Statut</th>
                                <th scope="col">Durée</th>
                                <th scope="col">Date début</th>
                                <th scope="col">Date fin prévue</th>
                                <th scope="col">Client</th>
                                <th scope="col">Développeur</th>
                                <th scope="col">Testeur</th>
                                <th scope="col">Stageur</th>
                                <th scope="col">Commentaire</th>
                                <th scope="col">Technologies</th>
                                <th scope="col">Progression</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="col">Projet 1</td>
                                <td class="col statut">
                                    <div class="test"></div>
                                    <span>Test</span>
                                </td>
                                <td class="col">x</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">Nom Prénom</td>
                                <td class="col">vigs1</td>
                                <td class="col">vigs2</td>
                                <td class="col">vigs3</td>
                                <td class="col">Commentaire</td>
                                <td class="col">WEB</td>
                                <td class="col"><span class="end_progress">90%</span></td>
                                <td class="col"><a href="./tasksFollowup.html"><button class="editBtn">Voir</button></a></td>
                            </tr>
                            <tr>
                                <td>Projet 2</td>
                                <td class="statut">
                                    <div class="prod"></div>
                                    <span>Prod</span>
                                </td>
                                <td class="col">x</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">Nom Prénom</td>
                                <td class="col">vigs1</td>
                                <td class="col">vigs2</td>
                                <td class="col">vigs3</td>
                                <td class="col">Commentaire</td>
                                <td class="col">WEB</td>
                                <td class="col"><span class="mid_progress">60%</span></td>
                                <td class="col"><a href="./tasksFollowup.html"><button class="editBtn">Voir</button></a></td>
                            </tr>
                            <tr>
                                <td>Projet 3</td>
                                <td class="statut">
                                    <div class="dev"></div>
                                    <span>Dev</span>
                                </td>
                                <td class="col">x</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">Nom Prénom</td>
                                <td class="col">vigs1</td>
                                <td class="col">vigs2</td>
                                <td class="col">vigs3</td>
                                <td class="col">Commentaire</td>
                                <td class="col">WEB</td>
                                <td class="col"><span class="mid_progress">50%</span></td>
                                <td class="col"><a href="./tasksFollowup.html"><button class="editBtn">Voir</button></a></td>
                            </tr>
                            <tr>
                                <td>Projet 4</td>
                                <td class="statut">
                                    <div class="stage"></div>
                                    <span>Stage</span>
                                </td>
                                <td class="col">x</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">Nom Prénom</td>
                                <td class="col">vigs1</td>
                                <td class="col">vigs2</td>
                                <td class="col">vigs3</td>
                                <td class="col">Commentaire</td>
                                <td class="col">WEB</td>
                                <td class="col"><span class="low_progress">25%</span></td>
                                <td class="col"><a href="./tasksFollowup.html"><button class="editBtn">Voir</button></a></td>
                            </tr>
                            <tr>
                                <td>Projet 5</td>
                                <td class="statut">
                                    <div class="prod"></div>
                                    <span>Prod</span>
                                </td>
                                <td class="col">x</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">Nom Prénom</td>
                                <td class="col">vigs1</td>
                                <td class="col">vigs2</td>
                                <td class="col">vigs3</td>
                                <td class="col">Commentaire</td>
                                <td class="col">WEB</td>
                                <td class="col"><span class="low_progress">5%</span></td>
                                <td class="col"><a href="./tasksFollowup.html"><button class="editBtn">Voir</button></a></td>
                            </tr>
                            <tr>
                                <td>Projet 6</td>
                                <td class="statut">
                                    <div class="cdc"></div>
                                    <span>CDC</span>
                                </td>
                                <td class="col">x</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">jj/mm/aaaa</td>
                                <td class="col">Nom Prénom</td>
                                <td class="col">vigs1</td>
                                <td class="col">vigs2</td>
                                <td class="col">vigs3</td>
                                <td class="col">Commentaire</td>
                                <td class="col">WEB</td>
                                <td class="col"><span class="end_progress">100%</span></td>
                                <td class="col"><a href="./tasksFollowup.html"><button class="editBtn">Voir</button></a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination mt-3">
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </main>

            <?php include _VIEW_PATH . "/components/footer.phtml";?>